"""
Factor Catalog (因子目录)

Central registry of named factors organized by 15 categories. Each factor
maps to a Qlib expression string generated by the operators in
``operators.py``.

Runtime universe — counts are DERIVED, never hard-coded. The catalog grows as
factors are added, so call ``catalog_composition()`` (below) for the live
``{base, composite, industry_relative, total}`` counts. It is the single source
of truth; tests and docs must call it rather than pin a magic number.

  - ``get_factor_catalog(include_new_data=False)`` → base factors (existing Qlib data only)
  - ``get_factor_catalog(include_new_data=True)``  → base factors + the new-alpha-endpoint
    families (flow_*, north_*, margin_*, earn_*, alpha_*) + the Round-6 sealed-OOS winners
    (liq_zero_ret_days_10d, rev_turnover_spike_5d, the 3 grow_*_yoy_accel_q,
    qual_piotroski_fscore_9pt — see ``_add_sealed_oos_winners``)
  - ``get_industry_relative_defs()``               → industry-relative composites
    (PIT-inherited from their ``base`` factor)
  - ``get_composite_defs()``                       → Layer-2 composites
    (PIT-inherited from their ``components`` list)
  - ``catalog_composition()``                      → the live count dict (single source of truth)

Catalog↔registry parity is enforced STRUCTURALLY by
``tests/alpha_research/test_factor_registry.py`` (sync output == catalog
composition, no duplicate ids, idempotent re-sync) — a factor-set change is
caught as drift without a magic number to hand-bump on every add.

Usage:
    catalog = get_factor_catalog()                       # base (existing-data) factors
    catalog = get_factor_catalog(include_new_data=True)  # base + new-data factors

    composites = get_composite_defs()                    # Layer-2 composites
    industry_rel = get_industry_relative_defs()          # industry-relative composites
    counts = catalog_composition()                       # live {base, composite, ...} counts
"""

from . import operators as op
from .hypothesis_factors import compile_to_qlib_expression, load_hypothesis_factor


def get_factor_catalog(include_new_data=False, include_hypothesis_factors: list[str] | None = None):
    """Return dict of {factor_name: qlib_expression_string}.

    All expressions include PIT-safe Ref(..., 1) shifts to prevent
    same-day leakage.

    Args:
        include_new_data: If True, include factors that require
            Phase 3 data downloads (cashflow, moneyflow, hk_hold,
            margin_detail, forecast, stk_holdernumber, stk_limit).
            Default False (only uses existing Qlib data).

    Returns:
        OrderedDict of {factor_name: expression_string}.
    """
    catalog = {}

    # ═══════════════════════════════════════════════════════════════
    # 1. MOMENTUM (动量) — 16 factors
    # ═══════════════════════════════════════════════════════════════
    for w in [5, 10, 20, 60, 120, 250]:
        catalog[f'mom_return_{w}d'] = op.momentum(w)

    catalog['mom_skip1m_252d'] = op.skip_momentum(21, 252)
    catalog['mom_weighted_120d'] = op.wma_return(120)
    catalog['mom_overnight_20d'] = op.overnight_return(20)
    catalog['mom_acceleration_20d'] = op.return_acceleration(20)
    catalog['mom_intraday_20d'] = op.intraday_return(20)
    catalog['mom_high_moment_20d'] = op.high_moment(20)
    catalog['mom_low_moment_20d'] = op.low_moment(20)
    catalog['mom_ewm_20d'] = op.ema_return(20)
    catalog['mom_ewm_60d'] = op.ema_return(60)
    # mom_idio_20d, mom_industry_rel_20d: implemented via
    # `get_industry_relative_defs()` + `operators.add_industry_relative_composites`
    # (Layer 2 post-processing — requires external SW2021 industry labels).

    # ── CICC price-volume 系列7 图表4 — momentum replication (E1a) ──
    # Genuinely-new constructions backed by P-OP-certified operators
    # (path_adjusted_momentum / up_down_day_share / ts_rank / days_since_high).
    # _M = 1 month (20d), _A = 1 year (250d). Linked into
    # config/replication/cicc_price_volume_cohort_v2.yaml by catalog_factor_id.
    # Dedup notes: mmt_normal_M≈mom_return_20d, mmt_normal_A≈mom_skip1m_252d,
    # mmt_intraday_M≈mom_intraday_20d, mmt_overnight_M≈mom_overnight_20d (NOT registered);
    # mmt_discrete_20d is rank-equivalent to rev_up_down_ratio_20d modulo flat-day handling
    # (registered anyway — the gate's resid_ic_vs_controls adjudicates redundancy empirically).
    catalog['mmt_route_20d'] = op.path_adjusted_momentum(20)        # mmt_route_M
    catalog['mmt_route_250d'] = op.path_adjusted_momentum(250)      # mmt_route_A
    catalog['mmt_discrete_20d'] = op.up_down_day_share(20)          # mmt_discrete_M
    catalog['mmt_discrete_250d'] = op.up_down_day_share(250)        # mmt_discrete_A
    catalog['mmt_time_rank_20d'] = f"Mean({op.ts_rank(250)}, 20)"   # mmt_time_rank_M: 20d-mean of 250d price rank
    catalog['mmt_highest_days_250d'] = op.days_since_high(250)      # mmt_highest_days_A

    # ── CICC price-volume 系列7 图表16 — volatility replication (E1b) ──
    # 13 subtypes × {20,60,120}d (1M/3M/6M); 36 registered (vol_std == risk_vol_{20,60,120}d EXACT
    # dedup, SKIPPED). vol_down/up_std = TRUE subset std (sign_conditional_std, limit-excluded via the
    # certified $limit_status field) — distinct from the zero-fill risk_downvol proxy. vol_highlow =
    # high/low (distinct from risk_range_ratio = (high-low)/close). Shadows via elementwise
    # Greater/Less (adjustment cancels in the ratio). GPT 5.5 Pro E1b factor-logic review APPROVED
    # (B1-B4 folded: full subset-std contract, $limit_status basis, 36-count, vol_std dedup lock).
    # Linked into config/replication/cicc_price_volume_cohort_v2.yaml.
    for w in [20, 60, 120]:
        catalog[f'vol_down_std_{w}d'] = op.sign_conditional_std("down", w)
        catalog[f'vol_up_std_{w}d'] = op.sign_conditional_std("up", w)
        catalog[f'vol_highlow_avg_{w}d'] = f"Mean({op.intraday_highlow()}, {w})"
        catalog[f'vol_highlow_std_{w}d'] = f"Std({op.intraday_highlow()}, {w})"
        catalog[f'vol_upshadow_avg_{w}d'] = f"Mean({op.norm_upper_shadow()}, {w})"
        catalog[f'vol_upshadow_std_{w}d'] = f"Std({op.norm_upper_shadow()}, {w})"
        catalog[f'vol_downshadow_avg_{w}d'] = f"Mean({op.norm_lower_shadow()}, {w})"
        catalog[f'vol_downshadow_std_{w}d'] = f"Std({op.norm_lower_shadow()}, {w})"
        catalog[f'vol_w_upshadow_avg_{w}d'] = f"Mean({op.williams_upper_shadow()}, {w})"
        catalog[f'vol_w_upshadow_std_{w}d'] = f"Std({op.williams_upper_shadow()}, {w})"
        catalog[f'vol_w_downshadow_avg_{w}d'] = f"Mean({op.williams_lower_shadow()}, {w})"
        catalog[f'vol_w_downshadow_std_{w}d'] = f"Std({op.williams_lower_shadow()}, {w})"

    # ═══════════════════════════════════════════════════════════════
    # 2. REVERSAL (短期反转) — 8 factors
    # ═══════════════════════════════════════════════════════════════
    for w in [1, 3, 5, 10]:
        catalog[f'rev_return_{w}d'] = op.short_reversal(w)

    catalog['rev_max_return_20d'] = op.max_single_return(20)
    catalog['rev_min_return_20d'] = op.min_single_return(20)
    catalog['rev_up_down_ratio_20d'] = op.up_down_ratio(20)
    # rev_consecutive_up → would need stateful Count logic (skip)

    # ═══════════════════════════════════════════════════════════════
    # 3. VALUE (价值) — 14 factors
    # ═══════════════════════════════════════════════════════════════
    catalog['val_ep_ttm'] = op.earnings_yield('ttm')
    catalog['val_ep'] = op.earnings_yield('static')
    catalog['val_bp'] = op.book_yield()
    catalog['val_sp_ttm'] = op.sales_yield('ttm')
    catalog['val_sp'] = op.sales_yield('static')
    catalog['val_div_yield'] = op.dividend_yield()
    catalog['val_div_ratio'] = op.dividend_ratio()
    catalog['val_cftp'] = op.ocf_yield()
    catalog['val_bps_to_price'] = op.bps_to_price()
    catalog['val_relative_pe'] = op.relative_valuation('pe_ttm', 750)
    catalog['val_pb_change_60d'] = op.valuation_change('pb', 60)
    # val_ep_industry_rel, val_bp_industry_rel: implemented via
    # `get_industry_relative_defs()` + `operators.add_industry_relative_composites`
    # (Layer 2 post-processing — requires external SW2021 industry labels).
    # val_fcf_yield, val_ev_ebitda, val_ebit_ev → need balance sheet fields
    # val_ocf_ev, val_capex_to_revenue, val_free_cashflow_yield → need cashflow

    # ═══════════════════════════════════════════════════════════════
    # 4. QUALITY (质量/盈利) — 16 factors
    # ═══════════════════════════════════════════════════════════════
    catalog['qual_roe'] = op.fundamental('roe')
    catalog['qual_roa'] = op.fundamental('roa')
    catalog['qual_roic'] = op.fundamental('roic')
    catalog['qual_gross_margin'] = op.fundamental('grossprofit_margin')
    catalog['qual_net_margin'] = op.fundamental('netprofit_margin')
    catalog['qual_asset_turnover'] = op.fundamental('assets_turn')
    catalog['qual_roe_stability'] = op.fundamental_stability('roe', 60)
    catalog['qual_margin_stability'] = op.fundamental_stability('grossprofit_margin', 60)
    catalog['qual_accruals'] = op.fundamental_ratio('ocfps', 'eps')
    catalog['qual_roe_change'] = op.fundamental_delta('roe', 1)
    catalog['qual_leverage'] = op.leverage_field('debt_to_assets')
    catalog['qual_current_ratio'] = op.leverage_field('current_ratio')
    catalog['qual_quick_ratio'] = op.leverage_field('quick_ratio')
    catalog['qual_margin_trend'] = op.fundamental_slope('grossprofit_margin', 4)
    # Novy-Marx (2013) gross-profits-to-assets = grossprofit_margin × assets_turn.
    # Idea-sourced (OSAP) then survived the marginal-contribution + orthogonal-residual
    # gates (residual ⟂ {gross_margin, asset_turn} RankICIR 0.174, |t|=7.2). Draft factor —
    # provenance: workspace/research/idea_sourcing/. Both fields approved (fina_indicator).
    catalog['qual_gross_profitability'] = "Ref($grossprofit_margin, 1) * Ref($assets_turn, 1)"
    # OSAP idea-sourced asset-composition gaps (Tier-1, 2026-06-08). Modest positive marginal
    # contribution vs the book (+0.019 / +0.017 increment, below the clean-orthogonal 0.02 bar but
    # NOT redundant); fill genuine gaps (balance-sheet cash intensity; R&D, of which the book had
    # none). Use the REGISTERED PIT-anchored statement fields (period-end _q0 / single-quarter
    # _sq_q0 from the income/balancesheet approved families), NOT the bare aliases — verified
    # bit-identical to the bare names (corr=1.0) but the _q0/_sq_q0 names are the field-registry's
    # PIT-correct, formal-eligible handles. Provenance: workspace/research/idea_sourcing/.
    catalog['qual_cash_to_assets'] = "Ref($money_cap_q0, 1) / Ref($total_assets_q0, 1)"
    catalog['qual_rd_to_assets'] = "Ref($rd_exp_sq_q0, 1) / Ref($total_assets_q0, 1)"
    # SINGLE-QUARTER margins (2026-06-09). The PIT-correct alternative to Tushare's vendor
    # q_netprofit_margin / q_gsprofit_margin single-quarter ratios: built from OUR single-quarter
    # _sq_q0 derivation (derive_single_quarter_value), which was parity-validated against the
    # vendor q_* (≈90% near-exact, Spearman 0.97-0.98 — see workspace/research/data_audit/
    # PIT_VS_VENDOR_Q_PARITY.md). Single-quarter margins capture recent-quarter profitability
    # shifts the cumulative grossprofit_margin/netprofit_margin smooth over. All fields are
    # field-approved income _sq_q0 (revenue/n_income_attr_p/oper_cost/operate_profit); each $field
    # is Ref(...,1)-wrapped for PIT safety. Draft factors.
    catalog['qual_q_net_margin'] = "Ref($n_income_attr_p_sq_q0, 1) / Ref($revenue_sq_q0, 1)"
    catalog['qual_q_gross_margin'] = "(Ref($revenue_sq_q0, 1) - Ref($oper_cost_sq_q0, 1)) / Ref($revenue_sq_q0, 1)"
    catalog['qual_q_op_margin'] = "Ref($operate_profit_sq_q0, 1) / Ref($revenue_sq_q0, 1)"

    # ═══════════════════════════════════════════════════════════════
    # CICC handbook replication batch (Phase D5, 2026-06-12) — 18 factors.
    # Constructions truth-certified against the 中金基本面手册 published tables
    # (exact-tier non-size IC 99% within tolerance over 2010-2022 × 3 domains;
    # workspace/research/cicc_replication/PHASE_D_ROUND1_REPORT.md). These are PIT
    # statement-slot TTM constructions — materially DIFFERENT from the vendor
    # cumulative-period indicator factors already in the catalog (qual_roa, val_ep_ttm
    # etc.): the Phase-C turnover fingerprint showed level constructions differ ~2× in
    # cross-section refresh cadence. Dedup mapping (CICC code ↔ catalog id, incl. the
    # 7 SKIPPED rank-identical codes): workspace/research/cicc_replication/D5_REGISTRATION_MAP.md.
    # NI_TTM uses n_income (incl. minority — attr_p has no q1-q3 slots; recorded caveat).
    # All claims on univ_all/csi300/csi500 are TAINTED post-hoc by construction (their
    # 2010-2022 IS evidence was observed in the replication batch before registration —
    # recorded in the TaintLedger; honest class per universe plan Draft-7).
    _ni_ttm = ("(Ref($n_income_sq_q0, 1) + Ref($n_income_sq_q1, 1)"
               " + Ref($n_income_sq_q2, 1) + Ref($n_income_sq_q3, 1))")
    _ocf_ttm = ("(Ref($n_cashflow_act_sq_q0, 1) + Ref($n_cashflow_act_sq_q1, 1)"
                " + Ref($n_cashflow_act_sq_q2, 1) + Ref($n_cashflow_act_sq_q3, 1))")
    _rev_ttm = ("(Ref($total_revenue_sq_q0, 1) + Ref($total_revenue_sq_q1, 1)"
                " + Ref($total_revenue_sq_q2, 1) + Ref($total_revenue_sq_q3, 1))")
    _rev_ttm_prev = ("(Ref($total_revenue_sq_q1, 1) + Ref($total_revenue_sq_q2, 1)"
                     " + Ref($total_revenue_sq_q3, 1) + Ref($total_revenue_sq_q4, 1))")
    _cost_ttm = ("(Ref($oper_cost_sq_q0, 1) + Ref($oper_cost_sq_q1, 1)"
                 " + Ref($oper_cost_sq_q2, 1) + Ref($oper_cost_sq_q3, 1))")
    _cost_ttm_prev = ("(Ref($oper_cost_sq_q1, 1) + Ref($oper_cost_sq_q2, 1)"
                      " + Ref($oper_cost_sq_q3, 1) + Ref($oper_cost_sq_q4, 1))")
    _capex_ttm = ("(Ref($c_pay_acq_const_fiolta_sq_q0, 1) + Ref($c_pay_acq_const_fiolta_sq_q1, 1)"
                  " + Ref($c_pay_acq_const_fiolta_sq_q2, 1) + Ref($c_pay_acq_const_fiolta_sq_q3, 1))")
    _avg_assets = "((Ref($total_assets_q0, 1) + Ref($total_assets_q4, 1)) / 2)"
    _mv_yuan = "(Ref($total_mv, 1) * 10000)"
    # 盈利/营运 levels (CICC: CFOA, ROA_TTM, NPM_TTM, AT, INVT, RAT, GPMD)
    catalog['qual_cfoa_ttm'] = f"{_ocf_ttm} / Ref($total_assets_q0, 1)"
    catalog['qual_roa_ttm'] = f"{_ni_ttm} / Ref($total_assets_q0, 1)"
    catalog['qual_npm_ttm'] = f"{_ni_ttm} / {_rev_ttm}"
    catalog['qual_at_ttm'] = f"{_rev_ttm} / {_avg_assets}"
    catalog['qual_invt_ttm'] = (f"{_cost_ttm} / ((Ref($inventories_q0, 1)"
                                " + Ref($inventories_q4, 1)) / 2)")
    catalog['qual_rat_ttm'] = (f"{_rev_ttm} / ((Ref($accounts_receiv_q0, 1)"
                               " + Ref($accounts_receiv_q4, 1)) / 2)")
    catalog['qual_gpmd_ttm'] = (f"(1 - {_cost_ttm}/{_rev_ttm})"
                                f" - (1 - {_cost_ttm_prev}/{_rev_ttm_prev})")
    # 盈余/安全 (CICC: CSR, CCR)
    catalog['qual_csr'] = "Ref($money_cap_q0, 1) / Ref($total_cur_liab_q0, 1)"
    catalog['qual_ccr_ttm'] = f"{_ocf_ttm} / Ref($total_cur_liab_q0, 1)"
    # 成长 single-quarter LEVELS (CICC: NP_Q_YOY/NP_QOQ/OP_Q_YOY/OR_Q_YOY/TA_YOY) — the
    # catalog so far held only their ACCELERATIONS (grow_*_yoy_accel_q = Delta of these).
    # Abs() denominators per the CICC convention (negative bases flip a plain ratio).
    catalog['grow_ni_attr_q_yoy'] = ("(Ref($n_income_attr_p_sq_q0, 1) - Ref($n_income_attr_p_sq_q4, 1))"
                                     " / Abs(Ref($n_income_attr_p_sq_q4, 1))")
    catalog['grow_ni_q_qoq'] = ("(Ref($n_income_sq_q0, 1) - Ref($n_income_sq_q1, 1))"
                                " / Abs(Ref($n_income_sq_q1, 1))")
    catalog['grow_op_q_yoy'] = ("(Ref($operate_profit_sq_q0, 1) - Ref($operate_profit_sq_q4, 1))"
                                " / Abs(Ref($operate_profit_sq_q4, 1))")
    catalog['grow_or_q_yoy'] = ("(Ref($total_revenue_sq_q0, 1) - Ref($total_revenue_sq_q4, 1))"
                                " / Abs(Ref($total_revenue_sq_q4, 1))")
    catalog['grow_total_assets_yoy'] = ("(Ref($total_assets_q0, 1) - Ref($total_assets_q4, 1))"
                                        " / Abs(Ref($total_assets_q4, 1))")
    # 估值 PIT-TTM (CICC: EP_TTM/OCFP_TTM/FCFP_TTM) — keep loss-makers ranked lowest
    # (1/pe_ttm drops them as NaN); TTM vs the vendor's cumulative-period basis.
    catalog['val_ep_ttm_pit'] = f"{_ni_ttm} / {_mv_yuan}"
    catalog['val_ocfp_ttm_pit'] = f"{_ocf_ttm} / {_mv_yuan}"
    catalog['val_fcfp_ttm'] = f"({_ocf_ttm} - {_capex_ttm}) / {_mv_yuan}"
    # 规模结构 (CICC: FC_MC 流通占比 — a bounded ratio, distinct from the ln-size levels)
    catalog['size_float_ratio'] = "Ref($circ_mv, 1) / Ref($total_mv, 1)"
    # CICC D4a — quarter-over-quarter TTM DIFFERENCE factors (Δ of the D5 levels = current-
    # quarter TTM ratio minus prior-quarter TTM ratio). The prior-quarter TTM uses the q1..q4
    # slots registered 2026-06-14 (register-only: bins materialized, same _sq/_q derivation as
    # the approved q0..q3/q0+q4 siblings — see approvals/2026-06-14_*; positional parity q1=prior /
    # q4=4th-prior + no-future-ann checked by workspace/scripts/canary_qslot_value_parity.py, R3).
    # FIDELITY TIERS (factor-logic cross-review R3, 2026-06-14 — cohort manifest v2):
    #   * CFOAD/ROAD/CCRD/CSRD/DAD/CURD — mechanically faithful (formula_equivalent_pending).
    #   * ROED/DTED/QRD — PROXIES (proxy_approx, hard candidate ceiling): see per-factor notes.
    #   * APRD — REMOVED (the prior qual_aprd was mis-built; see the batch-3 note below).
    _ni_ttm_prev = ("(Ref($n_income_sq_q1, 1) + Ref($n_income_sq_q2, 1)"
                    " + Ref($n_income_sq_q3, 1) + Ref($n_income_sq_q4, 1))")
    _ocf_ttm_prev = ("(Ref($n_cashflow_act_sq_q1, 1) + Ref($n_cashflow_act_sq_q2, 1)"
                     " + Ref($n_cashflow_act_sq_q3, 1) + Ref($n_cashflow_act_sq_q4, 1))")
    catalog['qual_cfoad'] = (f"{_ocf_ttm} / Ref($total_assets_q0, 1)"
                             f" - {_ocf_ttm_prev} / Ref($total_assets_q1, 1)")
    catalog['qual_road'] = (f"{_ni_ttm} / Ref($total_assets_q0, 1)"
                            f" - {_ni_ttm_prev} / Ref($total_assets_q1, 1)")
    catalog['qual_ccrd'] = (f"{_ocf_ttm} / Ref($total_cur_liab_q0, 1)"
                            f" - {_ocf_ttm_prev} / Ref($total_cur_liab_q1, 1)")
    # CSRD (现金比率变动): money_cap (货币资金, balance-sheet) is a close proxy for CICC's CSR
    # 现金及现金等价资产; its fidelity INHERITS the D5 CSR (qual_csr) source-line / truth-parity
    # assumption (if CICC CSR means cash-flow-statement cash-and-equivalents, money_cap is near but
    # not exact). Kept formula_equivalent_pending (per R3) contingent on that CSR=money_cap parity.
    catalog['qual_csrd'] = ("Ref($money_cap_q0, 1) / Ref($total_cur_liab_q0, 1)"
                            " - Ref($money_cap_q1, 1) / Ref($total_cur_liab_q1, 1)")
    # D4a batch-2 — leverage/liquidity ratio differences (CICC DAD/CURD/QRD). q1 slots
    # registered 2026-06-14 batch-2 (total_liab_q1 / total_cur_assets_q1 / inventories_q1).
    # qual_qrd is a PROXY (proxy_approx): CICC 速动比率 subtracts more from current assets
    # ((流动资产 − 存货 − 1年内到期非流动资产 − 待摊费用 − 预付款)/流动负债) than this
    # inventory-only quick ratio; those extra balance-sheet lines have no registered q0/q1 slots,
    # so this is the simplified inventory-only form, not the exact CICC quick ratio.
    catalog['qual_dad'] = ("Ref($total_liab_q0, 1) / Ref($total_assets_q0, 1)"
                           " - Ref($total_liab_q1, 1) / Ref($total_assets_q1, 1)")
    catalog['qual_curd'] = ("Ref($total_cur_assets_q0, 1) / Ref($total_cur_liab_q0, 1)"
                            " - Ref($total_cur_assets_q1, 1) / Ref($total_cur_liab_q1, 1)")
    catalog['qual_qrd'] = ("(Ref($total_cur_assets_q0, 1) - Ref($inventories_q0, 1)) / Ref($total_cur_liab_q0, 1)"
                           " - (Ref($total_cur_assets_q1, 1) - Ref($inventories_q1, 1)) / Ref($total_cur_liab_q1, 1)")
    # D4a batch-3 — ROE / debt-to-equity differences (CICC ROED/DTED). Equity uses
    # $total_hldr_eqy_inc_min_int (INCL-minority), matched to the incl-minority _ni_ttm numerator
    # (mixing total NI with 归母 equity would overstate ROE — same documented basis as qual_roa_ttm).
    # Both are PROXIES (proxy_approx): CICC ROE / 产权比率 are 归母 (exc-minority equity, and 归母
    # net profit). The exc_min_int equity slots AND the 归母-NI single-quarter slots are unregistered,
    # so the faithful 归母 form is not buildable yet — these are incl-minority approximations.
    # (CICC APRD 应计利润占比变动 was REMOVED here 2026-06-14/R3: the prior qual_aprd computed
    # payables turnover Δ(营业成本TTM / 应付账款), unrelated to the handbook's accruals ratio
    # 应计利润TTM / 营业利润TTM. The faithful build needs operate_profit_sq q1-q3 — only q0/q4 are
    # registered — plus a transcribed 应计利润 numerator; until then APRD stays un-built. The
    # accounts_pay_q0/q1 slots registered for it are now unconsumed — see the approval YAML note.)
    catalog['qual_roed'] = f"{_ni_ttm} / Ref($total_hldr_eqy_inc_min_int_q0, 1) - {_ni_ttm_prev} / Ref($total_hldr_eqy_inc_min_int_q1, 1)"
    catalog['qual_dted'] = ("Ref($total_liab_q0, 1) / Ref($total_hldr_eqy_inc_min_int_q0, 1)"
                            " - Ref($total_liab_q1, 1) / Ref($total_hldr_eqy_inc_min_int_q1, 1)")
    # qual_dupont, qual_operating_leverage → computed as Layer 2 composite
    # qual_ocf_to_ni → needs cashflow data

    # ═══════════════════════════════════════════════════════════════
    # 5. GROWTH (成长) — 14 factors
    # ═══════════════════════════════════════════════════════════════
    catalog['grow_revenue_yoy'] = op.fundamental('or_yoy')
    catalog['grow_netprofit_yoy'] = op.fundamental('netprofit_yoy')
    catalog['grow_opprofit_yoy'] = op.fundamental('op_yoy')
    catalog['grow_opprofit_qoq'] = op.fundamental('q_op_qoq')
    catalog['grow_eps_yoy'] = op.fundamental('basic_eps_yoy')
    catalog['grow_roe_yoy'] = op.fundamental('roe_yoy')
    catalog['grow_rev_acceleration'] = op.fundamental_delta('or_yoy', 1)
    catalog['grow_profit_acceleration'] = op.fundamental_delta('netprofit_yoy', 1)
    catalog['grow_consistency'] = op.fundamental_stability('netprofit_yoy', 60)
    catalog['grow_gross_margin_chg'] = op.fundamental_delta('grossprofit_margin', 1)
    catalog['grow_roe_improvement'] = op.fundamental_delta('roe', 4)
    catalog['grow_rev_trend'] = op.fundamental_slope('or_yoy', 4)
    catalog['grow_profit_trend'] = op.fundamental_slope('netprofit_yoy', 4)
    # grow_peg → valuation/growth ratio
    catalog['grow_peg'] = (
        f"0 - Ref($pe_ttm, 1) / Ref($netprofit_yoy, 1)"
    )

    # ═══════════════════════════════════════════════════════════════
    # 6. SIZE (规模) — 5 factors
    # ═══════════════════════════════════════════════════════════════
    catalog['size_ln_mcap'] = op.log_size('total_mv')
    catalog['size_ln_circmv'] = op.log_size('circ_mv')
    catalog['size_ln_mcap_sq'] = op.log_size_squared()
    catalog['size_ln_free_float'] = op.log_size('free_share')
    # size_relative_mcap → Layer 2 (needs cross-sectional median)

    # ═══════════════════════════════════════════════════════════════
    # 7. VOLATILITY / RISK (波动率/风险) — 14 factors
    # ═══════════════════════════════════════════════════════════════
    for w in [5, 10, 20, 60, 120]:
        catalog[f'risk_vol_{w}d'] = op.rolling_vol(w)

    catalog['risk_downvol_20d'] = op.downside_vol(20)
    catalog['risk_downvol_60d'] = op.downside_vol(60)
    catalog['risk_mdd_proxy_60d'] = op.max_drawdown_proxy(60)
    catalog['risk_vol_of_vol'] = op.vol_of_vol(20, 60)
    catalog['risk_var_95_20d'] = op.tail_risk(20, 0.05)
    catalog['risk_skew_60d'] = op.rolling_skew(60)
    catalog['risk_range_ratio_20d'] = op.range_ratio(20)
    catalog['risk_tail_60d'] = op.tail_risk(60, 0.05)
    # risk_beta_60d, risk_idio_vol → Layer 2 (need market return)
    # risk_corr_to_market, risk_upside_beta, risk_downside_beta → Layer 2

    # ═══════════════════════════════════════════════════════════════
    # 8. LIQUIDITY (流动性) — 14 factors
    # ═══════════════════════════════════════════════════════════════
    for w in [5, 10, 20, 60]:
        catalog[f'liq_turnover_{w}d'] = op.avg_turnover(w)

    catalog['liq_turnover_f_5d'] = op.avg_turnover(5, free_float=True)
    catalog['liq_turnover_f_20d'] = op.avg_turnover(20, free_float=True)
    catalog['liq_turnover_ratio_5_60'] = op.turnover_ratio(5, 60)
    catalog['liq_amihud_20d'] = op.amihud_illiquidity(20)
    catalog['liq_vol_cv_20d'] = op.volume_cv(20)
    catalog['liq_log_dollar_vol'] = op.log_dollar_volume(20)
    catalog['liq_vol_surge'] = op.volume_surge(5, 60)
    catalog['liq_vol_ratio_ma5'] = op.volume_ratio_smoothed(5)
    catalog['liq_turnover_skew_20d'] = op.turnover_skew(20)
    catalog['liq_spread_proxy_20d'] = op.spread_proxy(20)

    # CICC Wave E1c — liquidity手册 (图表28): 19 new (2 exact dedups: liq_turn_avg_{20,60} ==
    # liq_turnover_{20,60}d). Guarded inline (GPT B1/B2: NaN not inf on a non-positive denom),
    # adjusted-OHLC shortcut (B4). No custom operator. See E1c_factor_logic.md.
    catalog['liq_turn_avg_120d'] = op.avg_turnover(120)            # 20/60 dedup to liq_turnover_{20,60}d
    for w in (20, 60, 120):
        catalog[f'liq_turn_std_{w}d'] = op.turnover_std(w)
        catalog[f'liq_vstd_{w}d'] = op.liq_vstd(w)
        catalog[f'liq_amihud_avg_{w}d'] = op.amihud_illiquidity_avg(w)   # guarded; 20d NEW (!= legacy liq_amihud_20d)
        catalog[f'liq_amihud_std_{w}d'] = op.amihud_illiquidity_std(w)
        catalog[f'liq_shortcut_avg_{w}d'] = op.shortcut_illiquidity_avg(w)
        catalog[f'liq_shortcut_std_{w}d'] = op.shortcut_illiquidity_std(w)

    # CICC Wave E1d — 量价相关性手册 (图表40): 8 new (0 dedup). Inline Corr+Ref, NO custom operator
    # (GPT factor-logic APPROVE 2026-06-18; manifest drops the pre-registered lead_lag_corr). Single 20d
    # window (handbook chart 40 is 1M only). lead_lag_semantics — _post = price/return POSTerior (t+1) ⇒
    # TURNOVER leads; _prior = price/return PRIOR (t-1) ⇒ PRICE/RETURN leads (lead realized by shifting
    # the LEADING series back, never a forward Ref). See E1d_factor_logic.md.
    catalog['corr_price_turn_20d'] = op.corr_price_turn(20)               # sync: corr(turnover, adj close level)
    catalog['corr_price_turn_post_20d'] = op.corr_price_turn_post(20)     # turnover leads price
    catalog['corr_price_turn_prior_20d'] = op.corr_price_turn_prior(20)   # price leads turnover
    catalog['corr_ret_turn_20d'] = op.corr_ret_turn(20)                   # sync: corr(turnover, ret)
    catalog['corr_ret_turn_post_20d'] = op.corr_ret_turn_post(20)         # turnover leads return
    catalog['corr_ret_turn_prior_20d'] = op.corr_ret_turn_prior(20)       # return leads turnover
    catalog['corr_ret_turnd_20d'] = op.corr_ret_turnd(20)                 # sync: corr(Δturnover, ret)
    catalog['corr_ret_turnd_prior_20d'] = op.corr_ret_turnd_prior(20)     # return leads Δturnover

    # ═══════════════════════════════════════════════════════════════
    # 9. TECHNICAL (技术指标) — 14 factors
    # ═══════════════════════════════════════════════════════════════
    catalog['tech_rsi_6'] = op.rsi(6)
    catalog['tech_rsi_14'] = op.rsi(14)
    catalog['tech_rsi_28'] = op.rsi(28)
    catalog['tech_close_to_high_20d'] = op.distance_from_high(20)
    catalog['tech_close_to_low_20d'] = op.distance_from_low(20)
    catalog['tech_price_to_ma20'] = op.price_to_ma(20)
    catalog['tech_price_to_ma60'] = op.price_to_ma(60)
    catalog['tech_ma5_ma20_ratio'] = op.ma_ratio(5, 20)
    catalog['tech_ma20_ma60_ratio'] = op.ma_ratio(20, 60)
    catalog['tech_macd_signal'] = op.macd_hist(12, 26, 9)
    catalog['tech_bb_pct'] = op.range_position(20)
    catalog['tech_williams_r_14'] = op.williams_r(14)
    catalog['tech_kurt_20d'] = op.rolling_kurt(20)
    catalog['tech_skew_20d'] = op.rolling_skew(20)

    # ═══════════════════════════════════════════════════════════════
    # 10. LEVERAGE (杠杆/偿债) — 10 factors
    # ═══════════════════════════════════════════════════════════════
    catalog['lev_debt_to_assets'] = op.leverage_field('debt_to_assets')
    catalog['lev_current_ratio'] = op.leverage_field('current_ratio')
    catalog['lev_quick_ratio'] = op.leverage_field('quick_ratio')
    catalog['lev_deleverage'] = op.deleverage('debt_to_assets', 1)
    catalog['lev_debt_capacity'] = "1.0 - Ref($debt_to_assets, 1) / 100.0"
    # lev_debt_to_equity, lev_equity_multiplier, lev_ocf_to_debt,
    # lev_interest_coverage, lev_net_debt_to_ebitda, lev_interest_burden
    # → need balance sheet fields not yet in Qlib

    # ═══════════════════════════════════════════════════════════════
    # 11-14: NEW DATA FACTORS (require Phase 3 downloads)
    # ═══════════════════════════════════════════════════════════════
    if include_new_data:
        _add_capital_flow_factors(catalog)      # Cat 11: moneyflow
        _add_northbound_factors(catalog)         # Cat 12: hk_hold
        _add_margin_factors(catalog)             # Cat 13: margin_detail
        _add_earnings_event_factors(catalog)     # Cat 14: forecast, etc.
        _add_alpha_endpoint_factors(catalog)     # Cat 15: top_inst, stk_holdertrade, block_trade
        _add_sealed_oos_winners(catalog)         # Cat 16: Round-6 sealed-OOS-validated winners

    for spec_hash in include_hypothesis_factors or []:
        spec = load_hypothesis_factor(spec_hash)
        namespaced_id = f"hyp__{spec.spec_hash[:12]}__{spec.factor_id}"
        catalog[namespaced_id] = compile_to_qlib_expression(spec)
    return catalog


def catalog_composition(include_new_data: bool = True) -> dict[str, int]:
    """Live factor-catalog composition — the SINGLE SOURCE OF TRUTH for counts.

    Derived from the catalog functions so it auto-updates as factors are added.
    NEVER hard-code these numbers in tests/docs — call this instead. Returns
    ``{"base", "composite", "industry_relative", "total"}`` where ``total`` is
    the named-factor surface area (= what ``sync_catalog`` registers).
    """
    n_base = len(get_factor_catalog(include_new_data=include_new_data))
    n_comp = len(get_composite_defs())
    n_ind = len(get_industry_relative_defs())
    return {"base": n_base, "composite": n_comp,
            "industry_relative": n_ind, "total": n_base + n_comp + n_ind}


def _add_capital_flow_factors(catalog):
    """Category 11: Capital Flow (资金流向) — requires moneyflow data."""
    for w in [5, 20]:
        catalog[f'flow_net_inflow_{w}d'] = f"Mean(Ref($net_mf_amount, 1), {w})"
    catalog['flow_large_net_pct_20d'] = (
        "Mean(Ref((($buy_lg_amount - $sell_lg_amount) / $amount), 1), 20)"
    )
    catalog['flow_small_net_pct_20d'] = (
        "Mean(Ref((($buy_sm_amount - $sell_sm_amount) / $amount), 1), 20)"
    )
    catalog['flow_large_small_ratio'] = (
        "Mean(Ref(($buy_lg_amount - $sell_lg_amount), 1), 20) / "
        "Mean(Ref(($buy_sm_amount - $sell_sm_amount), 1), 20)"
    )
    catalog['flow_inflow_surge'] = (
        "Mean(Ref($net_mf_amount, 1), 5) / Mean(Ref($net_mf_amount, 1), 60)"
    )
    catalog['flow_large_buy_ratio_5d'] = (
        "Mean(Ref($buy_lg_amount, 1), 5) / Mean(Ref($amount, 1), 5)"
    )


def _add_northbound_factors(catalog):
    """Category 12: Northbound Funds (北向资金) — requires hk_hold data."""
    catalog['north_hold_pct'] = "Ref($ratio, 1)"
    catalog['north_hold_change_5d'] = "Ref($ratio, 1) - Ref($ratio, 6)"
    catalog['north_hold_change_20d'] = "Ref($ratio, 1) - Ref($ratio, 21)"
    catalog['north_accumulation_20d'] = "Sum(Delta(Ref($ratio, 1), 1), 20)"
    catalog['north_flow_momentum'] = "Slope(Ref($ratio, 1), 20)"
    # Within-coverage variants (arXiv D4, 2026-06-10): the provider zero-densifies
    # $ratio for non-Connect names (~half the universe ties at 0), diluting the
    # unmasked forms above (size-neut ICIR 0.20 -> 0.47 once masked). Mask to the
    # held sub-universe via If(ratio>0, ..., np.nan); rank within-coverage is then
    # automatic. Marginal increment +0.019 vs the 31-factor book (just under the
    # +0.02 bar) -> drafts pending the IS lifecycle gate. Expected sign: + (foreign
    # accumulation -> continuation). See idea_sourcing/knowledge/D1_D4_SCREEN_RESULTS.md.
    catalog['north_hold_change_20d_cov'] = (
        "If(Ref($ratio, 1) > 0, Ref($ratio, 1) - Ref($ratio, 21), np.nan)"
    )
    catalog['north_hold_change_60d_cov'] = (
        "If(Ref($ratio, 1) > 0, Ref($ratio, 1) - Ref($ratio, 61), np.nan)"
    )


def _add_margin_factors(catalog):
    """Category 13: Margin Trading (融资融券) — requires margin_detail data."""
    catalog['margin_balance_pct'] = "Ref($rzye, 1) / Ref($circ_mv, 1)"
    catalog['margin_net_buy_20d'] = "Mean(Ref(($rzmre - $rzche), 1), 20)"
    catalog['margin_sl_balance_change'] = "Delta(Ref($rqye, 1), 20)"


def _report_rc_eps_diffusion(window, min_n=3, min_active=2):
    """report_rc analyst EPS-revision breadth (eps_diffusion): net % of analysts RAISING
    their FY1 EPS over `window` trading days, gated on >= min_n revisions AND >= min_active
    live analysts. Built from the approved $report_rc__* event-flow primitives; each field is
    Ref(...,1)-wrapped (on top of the provider's report_date+1 anchor) per the field-registry
    PIT contract. Sparse event feed -> Sum(If(x==x,x,0), W) zero-fills no-event days; ineligible
    rows -> np.nan (drop from the cross-section, NOT 0). Verified bit-identical to the sandbox
    screen (corr 1.0). Coverage is cap-tilted (~27% @60d) -> size-neutralize when used."""
    up = "Ref($report_rc__eps_up, 1)"; dn = "Ref($report_rc__eps_dn, 1)"
    rc = "Ref($report_rc__eps_revision_count, 1)"; act = "Ref($report_rc__n_active_analysts, 1)"
    z = lambda x: f"If(({x}) == ({x}), ({x}), 0)"          # NaN!=NaN -> 0 (zero-fill no-event days)
    up_w, dn_w, n_w = f"Sum({z(up)}, {window})", f"Sum({z(dn)}, {window})", f"Sum({z(rc)}, {window})"
    enough = f"({n_w} >= {min_n})"; active = f"({act} >= {min_active})"
    denom = f"If({enough}, {n_w}, 1)"; raw = f"(({up_w} - {dn_w}) / {denom})"
    return f"If({enough}, If({active}, {raw}, np.nan), np.nan)"


def _add_earnings_event_factors(catalog):
    """Category 14: Earnings/Events — requires forecast, holder data."""
    # Earnings surprise (can be computed from existing EPS data)
    catalog['earn_surprise_eps'] = "Ref($eps, 1) / Ref($eps, 5) - 1"
    catalog['earn_surprise_revenue'] = "Ref($or_yoy, 1)"
    catalog['earn_earnings_momentum'] = (
        "If(Ref($netprofit_yoy, 1) > 0, "
        "If(Ref($netprofit_yoy, 2) > 0, 1, 0), 0)"
    )
    # report_rc analyst EPS-revision breadth (eps_diffusion) — idea-sourced (OSAP→report_rc),
    # 2026-06-08: the FIRST genuinely-new-dimension draft. Size-neut IS ICIR ~0.55 (60d) /
    # ~0.46 (120d); SURVIVES orthogonalization to ROE/growth (residual retains ~100-105%) →
    # analyst-revision info beyond known fundamentals. $report_rc__* approved 2026-06-09.
    # ⚠ sealed-OOS (candidate→approved) is HARD-GATED behind the 2026-06-15 breadth canary.
    catalog['earn_eps_diffusion_60'] = _report_rc_eps_diffusion(60)
    catalog['earn_eps_diffusion_120'] = _report_rc_eps_diffusion(120)
    # Scaled SUE / PEAD (arXiv D3, 2026-06-10): YoY change in single-quarter
    # attributable net income scaled by market cap / total assets — the classic
    # 8-quarter SUE is NOT buildable (income family serves n_income_sq only to q3;
    # attr_p has exactly q0+q4). Strongest standalone of the D1-D4 run (size-neut
    # ICIR 0.50/0.30, beats plain YoY growth by +0.20) BUT payoff-corr 0.92/0.95 to
    # grow_netprofit_yoy -> explicitly a GROWTH-FAMILY REFINEMENT, not a new
    # dimension (marginal increment +0.015/+0.020). Statement fields are
    # PIT-anchored on max(ann_date, f_ann_date); Ref(...,1) on top per the registry
    # contract. Expected sign: + (PEAD drift). See D1_D4_SCREEN_RESULTS.md.
    catalog['earn_sue_ni_mcap'] = (
        "(Ref($n_income_attr_p_sq_q0, 1) - Ref($n_income_attr_p_sq_q4, 1)) "
        "/ Ref($total_mv, 1)"
    )
    catalog['earn_sue_ni_assets'] = (
        "(Ref($n_income_attr_p_sq_q0, 1) - Ref($n_income_attr_p_sq_q4, 1)) "
        "/ Ref($total_assets_q0, 1)"
    )


def _add_sealed_oos_winners(catalog):
    """Category 16: Round-6 sealed-OOS-validated winners (onboarded 2026-06-02).

    These 6 factors are the ONLY factors in the system with genuine, formal-path,
    single-shot sealed-OOS evidence: an IS screen (2014-2020) froze a 13-factor top
    set BEFORE the OOS window (2021-01-01 -> 2026-02-27) was run exactly once through
    the sanctioned ``compute_factors(oos_test)`` -> ``qlib_windowed_features`` path.
    6 passed the pre-declared gate (sign-stable IS->OOS in both IC and LS Sharpe, AND
    OOS long-short Sharpe > 1.0). Evidence: ``oos_results_and_registration.md``,
    ``oos_frozen_topset.json`` (frozen pre-OOS at commit 73d556a).

    The expression strings here are VERBATIM the strings the sealed OOS validated
    (``factor_candidates_merged.csv`` ``qlib_expression`` column) so the promotion
    gate's definition-binding (catalog hash == frozen-artifact hash) holds. All are
    ``Ref(..., 1)``-wrapped (PIT-safe) and resolve to ``approved`` datasets
    (market_daily / daily_basic / pit_fundamentals) at ``formal_validation``.

    NOTE the 3 ``grow_*_yoy_accel_q`` are growth-ACCELERATION (1-quarter Delta of the
    YoY rate); the growth-LEVEL ``grow_*_yoy_q`` factors were IS-overfit OOS-collapsers
    (Phase 6) — a different signal. Do not confuse them.
    """
    # Liquidity (Lesmond zero-return illiquidity; sign-stable, strengthened OOS).
    catalog['liq_zero_ret_days_10d'] = (
        "Sum(If(Abs((Ref(($close * $adj_factor), 1) / "
        "Ref(($close * $adj_factor), 2) - 1)) < 0.0001, 1, 0), 10) / 10"
    )
    # Reversal x turnover-spike (microstructure; no OOS decay, retain 103%).
    catalog['rev_turnover_spike_5d'] = (
        "0 - ((Ref(($close * $adj_factor), 1) / Ref(($close * $adj_factor), 6) - 1) "
        "* (Mean(Ref($turnover_rate_f, 1), 5) / Mean(Ref($turnover_rate_f, 1), 60)))"
    )
    # Growth acceleration (1-quarter Delta of the single-quarter YoY rate).
    catalog['grow_total_revenue_yoy_accel_q'] = (
        "Delta(Ref($total_revenue_sq_q0, 1) / Ref($total_revenue_sq_q4, 1) - 1, 63)"
    )
    catalog['grow_n_income_attr_p_yoy_accel_q'] = (
        "Delta(Ref($n_income_attr_p_sq_q0, 1) / Ref($n_income_attr_p_sq_q4, 1) - 1, 63)"
    )
    catalog['grow_operate_profit_yoy_accel_q'] = (
        "Delta(Ref($operate_profit_sq_q0, 1) / Ref($operate_profit_sq_q4, 1) - 1, 63)"
    )
    # Quality (Piotroski F-score, 9-term; classic composite, holds OOS).
    catalog['qual_piotroski_fscore_9pt'] = (
        "If(Ref($n_income_attr_p_sq_q0, 1) > 0, 1, 0) "
        "+ If(Ref($n_cashflow_act_sq_q0, 1) > 0, 1, 0) "
        "+ If(Ref($n_cashflow_act_sq_q0, 1) > Ref($n_income_attr_p_sq_q0, 1), 1, 0) "
        "+ If(Ref($n_income_attr_p_sq_q0, 1) / Ref($total_assets_q0, 1) > "
        "Ref($n_income_attr_p_sq_q4, 1) / Ref($total_assets_q4, 1), 1, 0) "
        "+ If(Ref($total_liab_q0, 1) / Ref($total_assets_q0, 1) < "
        "Ref($total_liab_q4, 1) / Ref($total_assets_q4, 1), 1, 0) "
        "+ If(Ref($total_cur_assets_q0, 1) / Ref($total_cur_liab_q0, 1) > "
        "Ref($total_cur_assets_q4, 1) / Ref($total_cur_liab_q4, 1), 1, 0) "
        "+ If(Ref($total_share, 1) <= Ref($total_share, 251), 1, 0) "
        "+ If((Ref($total_revenue_sq_q0, 1) - Ref($oper_cost_sq_q0, 1)) / "
        "Ref($total_revenue_sq_q0, 1) > (Ref($total_revenue_sq_q4, 1) - "
        "Ref($oper_cost_sq_q4, 1)) / Ref($total_revenue_sq_q4, 1), 1, 0) "
        "+ If(Ref($total_revenue_sq_q0, 1) / Ref($total_assets_q0, 1) > "
        "Ref($total_revenue_sq_q4, 1) / Ref($total_assets_q4, 1), 1, 0)"
    )


def get_industry_relative_defs() -> list[dict]:
    """Registry of Layer 2 industry-relative factors.

    These factors require external time-varying SW2021 industry labels
    (from `provider_metadata.build_industry_series_asof`) and cannot be
    expressed as pure Qlib expressions. They live OUTSIDE
    ``get_factor_catalog()`` and ``get_composite_defs()`` and are computed
    by ``operators.add_industry_relative_composites()``.

    PIT safety: each def references a ``base`` factor that already lives
    in ``get_factor_catalog()`` and is enforced PIT-safe by the parser.
    The Layer 2 transform (industry-mean subtract or size+industry
    neutralize) does not introduce any new ``$field`` references, so
    PIT-safety is inherited from the base.

    Schema:
        name: factor name (e.g., 'mom_industry_rel_20d')
        base: name of the base factor in `get_factor_catalog()`
        kind: 'industry_mean_subtract' | 'size_industry_neutralize'
        requires_market_cap: bool (True only for size_industry_neutralize)

    Consumers:
        - `operators.add_industry_relative_composites` (compute)
        - `event_driven_strategy_research.get_required_catalog` (schema check)
        - `event_driven_strategy_research.build_factor_meta` (category meta)
        - `tests.test_factor_library_pit_safety` (parser enumeration)

    Plan ref: vast-exploring-rabbit v8 phase B3.
    """
    return [
        {
            "name": "mom_industry_rel_20d",
            "base": "mom_return_20d",
            "kind": "industry_mean_subtract",
            "requires_market_cap": False,
        },
        {
            "name": "mom_idio_20d",
            "base": "mom_return_20d",
            "kind": "size_industry_neutralize",
            "requires_market_cap": True,
        },
        {
            "name": "val_ep_industry_rel",
            "base": "val_ep_ttm",
            "kind": "industry_mean_subtract",
            "requires_market_cap": False,
        },
        {
            "name": "val_bp_industry_rel",
            "base": "val_bp",
            "kind": "industry_mean_subtract",
            "requires_market_cap": False,
        },
    ]


def _add_alpha_endpoint_factors(catalog):
    """Category 15: Alpha Endpoints (机构/股东/大宗) — requires the 5 new
    alpha endpoints bootstrapped 2026-04-15/16 and the 2026-04-20 namespace
    fix in `pit_backend.py::_materialize_daily_dataset` (event-like daily
    columns are prefixed `<dataset>__<col>` in the Qlib provider).

    Sparse-by-design: each factor's underlying field is NaN on days the
    event did not occur. Sum/Mean rolling windows aggregate across the
    sparse event days within the lookback.
    """
    # Net institutional buy amount aggregated over 20 days (top_inst).
    # Higher = more institutional accumulation on 龙虎榜 days.
    catalog['alpha_inst_net_buy_20d'] = "Sum(Ref($top_inst__net_buy, 1), 20)"

    # Net insider holder change as % of float, aggregated over 60 days
    # (stk_holdertrade). Higher = net insider accumulation. Uses the
    # cross-sectionally comparable ratio (% of float), not raw share count.
    # `holdertrade_net_ratio` comes from the dedicated
    # `_materialize_stk_holdertrade` aggregator (no `__` prefix because it
    # is not a generic daily-fact endpoint).
    catalog['alpha_insider_net_buy_60d'] = "Sum(Ref($holdertrade_net_ratio, 1), 60)"

    # Average block-trade discount to close over 20 days (block_trade).
    # Discount = 1 - block_price / raw_close. Both sides are RAW (unadjusted)
    # because block_trade__price is the raw block-trade execution price as
    # reported by Tushare; dividing by adjusted close would inflate the
    # discount on older data where adj_factor is large. Sign is intentionally
    # ambiguous and will be determined by Phase 1 screening: deep discounts
    # could signal insider distribution (bearish) OR liquidity-driven
    # institutional accumulation (bullish).
    catalog['alpha_block_discount_20d'] = (
        "Mean(1 - Ref($block_trade__price, 1) / Ref($close, 1), 20)"
    )

    # ── Chip distribution (cyq_perf, dense daily coverage) ──────────────
    # 20-day change in winner_rate (share of holders at profit). Positive =
    # rising profit base, often precedes distribution; Negative = trapped
    # holders, potential bottom signal. Monotonicity ambiguous — to screen.
    catalog['alpha_chip_winner_rate_chg_20d'] = (
        "Delta(Ref($cyq_perf__winner_rate, 1), 20)"
    )

    # Chip concentration (inverse): cost spread (95pct-5pct) relative to the
    # median cost. Higher = chips spread wider, less concentration. Typically
    # correlates with uncertainty / range-bound regimes.
    catalog['alpha_chip_cost_spread_pct'] = (
        "(Ref($cyq_perf__cost_95pct, 1) - Ref($cyq_perf__cost_5pct, 1)) "
        "/ Ref($cyq_perf__cost_50pct, 1)"
    )

    # Close position relative to the median-cost chip. Positive = price above
    # cost_50pct (holders at profit, potential distribution pressure);
    # Negative = below cost_50pct (trapped holders, potential squeeze).
    catalog['alpha_chip_price_vs_cost50'] = (
        "(Ref($close, 1) - Ref($cyq_perf__cost_50pct, 1)) "
        "/ Ref($cyq_perf__cost_50pct, 1)"
    )

    # Close vs cost-weighted-average deviation. Signed distance from the
    # holder-weighted mean cost. Cleaner than `price_vs_cost50` when cost
    # distribution is skewed.
    catalog['alpha_chip_weight_avg_dev'] = (
        "(Ref($close, 1) - Ref($cyq_perf__weight_avg, 1)) "
        "/ Ref($cyq_perf__weight_avg, 1)"
    )

    # 10-day EMA of winner_rate for smoothed signal. Sparse-day noise
    # reduction on the already-dense cyq_perf field.
    catalog['alpha_chip_winner_rate_ema_10d'] = (
        "EMA(Ref($cyq_perf__winner_rate, 1), 10)"
    )

    # 20d-smoothed Grinblatt-Han Capital Gains Overhang (arXiv D1 winner,
    # 2026-06-10): the smoothed variant of `alpha_chip_weight_avg_dev` above.
    # The D1-D4 exploration's top result — marginal increment +0.047 vs the
    # 31-factor book (2018-2020 overlap window; 2x the GP precedent), size-neut
    # ICIR +0.35, Grinblatt-Han sign (+) confirms in A-shares. Caveats carried
    # into the lifecycle: cyq_perf coverage floor makes IS 2018+ only, and the
    # 0.88 payoff-corr to qual_roa is period-confounded (2018-2020 quality
    # rally). Expected sign: + (gain overhang -> continuation). See
    # idea_sourcing/knowledge/D1_D4_SCREEN_RESULTS.md.
    catalog['alpha_chip_cgo_smooth_20d'] = (
        "Mean((Ref($close, 1) - Ref($cyq_perf__weight_avg, 1)) "
        "/ Ref($cyq_perf__weight_avg, 1), 20)"
    )

    # ── Insider / holder transactions (stk_holdertrade aggregates) ──────
    # 60-day absolute volume — insider activity level independent of
    # direction. High values flag heightened disclosure activity.
    catalog['alpha_holder_gross_vol_60d'] = (
        "Sum(Ref($holdertrade_gross_vol, 1), 60)"
    )

    # 60-day count of holder-disclosure events. Attention proxy — more
    # disclosures = more insider activity, regardless of direction.
    catalog['alpha_holder_event_density_60d'] = (
        "Sum(Ref($holdertrade_events, 1), 60)"
    )

    # 20-day EMA of signed holder-change ratio. Smoothed net insider
    # direction (signed % of float).
    catalog['alpha_holder_net_ratio_ema_20d'] = (
        "EMA(Ref($holdertrade_net_ratio, 1), 20)"
    )

    # ── Top-list / 龙虎榜 retail-view (top_list, sparse) ────────────────
    # 20-day mean of net_rate (net-buy rate on 龙虎榜 days). Sparse by design;
    # NaN on days with no 龙虎榜 appearance. Mean averages across event days.
    catalog['alpha_toplist_net_rate_20d'] = (
        "Mean(Ref($top_list__net_rate, 1), 20)"
    )

    # 20-day mean 龙虎榜 amount over total market cap. Measures size-
    # normalized 龙虎榜 flow intensity. Larger ratios = more notable 龙虎榜
    # participation relative to stock's float.
    catalog['alpha_toplist_amount_over_mv_20d'] = (
        "Mean(Ref($top_list__l_amount, 1) / Ref($total_mv, 1), 20)"
    )

    # 60-day 龙虎榜 appearance density. NaN-equality inversion used instead
    # of `IsNull` (which is not in `qlib.data.ops`); `NaN == NaN → False`,
    # so `If(x == x, 1, 0)` returns 1 on non-NaN (event) days and 0 on NaN
    # (non-event) days. Sum over 60 days = event count in window.
    catalog['alpha_toplist_hit_density_60d'] = (
        "Sum(If(Ref($top_list__l_amount, 1) == Ref($top_list__l_amount, 1), 1, 0), 60)"
    )

    # ── Top-inst / 龙虎榜机构 (top_inst, sparse) ─────────────────────────
    # 20-day EMA of net institutional buy amount on 龙虎榜 days.
    # Complements the existing `alpha_inst_net_buy_20d` (20-day Sum) by
    # emphasizing recent institutional flow with exponential decay.
    catalog['alpha_topinst_net_buy_ema_20d'] = (
        "EMA(Ref($top_inst__net_buy, 1), 20)"
    )

    # 60-day institutional 龙虎榜 appearance count — same NaN-equality
    # inversion trick as `alpha_toplist_hit_density_60d`.
    catalog['alpha_topinst_hit_density_60d'] = (
        "Sum(If(Ref($top_inst__net_buy, 1) == Ref($top_inst__net_buy, 1), 1, 0), 60)"
    )

    # ── Block trade (block_trade, sparse) ───────────────────────────────
    # 20-day mean of block-trade volume as fraction of the daily volume.
    # Both numerator (block_trade__vol) and denominator (daily $vol) are
    # shifted T-1. Captures the intensity of block-trade activity relative
    # to normal liquidity.
    catalog['alpha_block_volume_share_20d'] = (
        "Mean(Ref($block_trade__vol, 1) / Ref($vol, 1), 20)"
    )

    # 20-day block-trade event density — NaN-equality inversion trick.
    catalog['alpha_block_event_density_20d'] = (
        "Sum(If(Ref($block_trade__amount, 1) == Ref($block_trade__amount, 1), 1, 0), 20)"
    )


def get_composite_defs():
    """Return composite factor definitions for Layer 2 computation.

    Each entry is a dict with:
        name: Factor name (comp_ prefix).
        components: List of Layer 1 factor names to combine.
        weights: Optional list of weights (default: equal weight).
        negate: List of booleans indicating which components to negate
                before ranking (e.g. True for size → small cap premium).

    Returns:
        List of composite definition dicts.
    """
    return [
        # ── Value + Quality ──
        {
            'name': 'comp_val_qual',
            'components': ['val_ep_ttm', 'qual_roe'],
        },
        # ── Value + Momentum ──
        {
            'name': 'comp_val_mom',
            'components': ['val_ep_ttm', 'mom_return_120d'],
        },
        # ── Quality + Growth ──
        {
            'name': 'comp_qual_grow',
            'components': ['qual_roe', 'grow_revenue_yoy'],
        },
        # ── Quality + Low Vol (Defensive) ──
        {
            'name': 'comp_defensive',
            'components': ['qual_roe', 'risk_vol_20d'],
            'negate': [False, True],  # negate vol → low vol ranks high
        },
        # ── Small Cap + Value ──
        {
            'name': 'comp_small_value',
            'components': ['size_ln_mcap', 'val_bp'],
            'negate': [True, False],  # negate size → small cap ranks high
        },
        # ── GARP (Growth at Reasonable Price) ──
        {
            'name': 'comp_garp',
            'components': ['grow_netprofit_yoy', 'val_ep_ttm', 'qual_roe'],
            'weights': [1/3, 1/3, 1/3],
        },
        # ── Reversal + Low Turnover ──
        {
            'name': 'comp_rev_low_turn',
            'components': ['rev_return_5d', 'liq_turnover_20d'],
            'negate': [False, True],
        },
        # ── Multi-Factor 6 ──
        {
            'name': 'comp_multi_6',
            'components': [
                'val_ep_ttm', 'qual_roe', 'grow_netprofit_yoy',
                'mom_return_60d', 'risk_vol_20d', 'size_ln_mcap',
            ],
            'negate': [False, False, False, False, True, True],
            'weights': [1/6] * 6,
        },
        # ── Magic Formula (Greenblatt) ──
        {
            'name': 'comp_magic_formula',
            'components': ['qual_roic', 'val_ep_ttm'],
        },
        # ── Quality × Value ──
        {
            'name': 'comp_quality_value',
            'components': ['qual_roe', 'val_bp'],
        },
        # ── Growth × Value ──
        {
            'name': 'comp_growth_value',
            'components': ['grow_revenue_yoy', 'val_ep_ttm'],
        },
        # ── Momentum × Quality ──
        {
            'name': 'comp_momentum_quality',
            'components': ['mom_return_120d', 'qual_roe'],
        },
        # ── Low Vol × Value ──
        {
            'name': 'comp_low_vol_value',
            'components': ['risk_vol_60d', 'val_ep_ttm'],
            'negate': [True, False],
        },
        # ── Quality + Growth ──
        {
            'name': 'comp_quality_growth',
            'components': ['qual_roe', 'grow_revenue_yoy'],
        },
        # ── Cash Sheep (OCF + Dividend) ──
        {
            'name': 'comp_cash_sheep',
            'components': ['val_cftp', 'val_div_yield'],
        },
        # ── Anti-Risk (Low leverage + High current ratio) ──
        {
            'name': 'comp_anti_risk',
            'components': ['lev_debt_to_assets', 'lev_current_ratio'],
            'negate': [True, False],
        },
        # ── Small × Quality ──
        {
            'name': 'comp_size_quality',
            'components': ['size_ln_mcap', 'qual_roe'],
            'negate': [True, False],
        },
        # ── Momentum × Reversal (trend + pullback) ──
        {
            'name': 'comp_momentum_reversal',
            'components': ['mom_return_120d', 'rev_return_5d'],
        },
        # ── Relative strength (stock vs market proxy) ──
        {
            'name': 'comp_relative_strength',
            'components': ['mom_return_20d', 'risk_vol_20d'],
            'negate': [False, True],
        },
        # ── 52-week metrics ──
        {
            'name': 'comp_52w_position',
            'components': ['tech_close_to_high_20d', 'tech_close_to_low_20d'],
            'weights': [0.5, 0.5],
        },
        # ── CICC handbook composite: Profit 综合盈利因子 = CFOA + ROE + ROIC 等权 (手册 §11) ──
        # PROXY (proxy_approx — HARD candidate_ceiling cap in cohort manifest v2; factor-logic R3).
        # This is NOT a faithful CICC Profit: it rank-combines a PIT-TTM CFOA (qual_cfoa_ttm) with the
        # VENDOR cumulative-YTD ROE/ROIC (qual_roe/qual_roic = fina_indicator) — a time-basis mismatch
        # (TTM vs YTD sawtooth). An exact TTM-ROIC is not cleanly buildable (handbook flags ROIC
        # ⚠️投入资本口径). Do NOT trust this prose as "faithful"; the manifest tier is the source of truth.
        # The other handbook composites are also not cleanly buildable yet — Growth needs OP_SD/QPT,
        # Opt needs OCFA (regression operator), QQC needs all six; Acc/Safe are single-base
        # (rank-equivalent to grow_profit_acceleration / qual_ccr_ttm → not registered, dedup discipline).
        {
            'name': 'comp_cicc_profit',
            'components': ['qual_cfoa_ttm', 'qual_roe', 'qual_roic'],
        },
    ]


def get_category_map():
    """Return dict mapping each factor name to its category.

    Returns:
        Dict of {factor_name: category_string}.
    """
    catalog = get_factor_catalog(include_new_data=True)
    mapping = {}
    for name in catalog:
        prefix = name.split('_')[0]
        category_map = {
            'mom': 'Momentum',
            'rev': 'Reversal',
            'val': 'Value',
            'qual': 'Quality',
            'grow': 'Growth',
            'size': 'Size',
            'risk': 'Volatility',
            'liq': 'Liquidity',
            'tech': 'Technical',
            'lev': 'Leverage',
            'flow': 'Capital Flow',
            'north': 'Northbound',
            'margin': 'Margin',
            'earn': 'Earnings',
            'comp': 'Composite',
        }
        mapping[name] = category_map.get(prefix, 'Other')
    return mapping
